sudo: required
services:
- docker
env:
  DOCKER_COMPOSE_VERSION: 1.23.2
before_install:
- openssl aes-256-cbc -K $encrypted_b3bfd8ea431a_key -iv $encrypted_b3bfd8ea431a_iv -in flask.env.enc -out flask.env -d
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
before_script:
- docker-compose -f docker-compose-dev.yml up --build -d
- export CI=true
script:
- docker-compose -f docker-compose-dev.yml exec flask-api python -m pytest
- docker-compose -f docker-compose-dev.yml exec client npm test
after_script: docker-compose -f docker-compose-dev.yml down
