version: '3'
services:
  db:
    image: db-trans-dev
    build:
      context: back_end/db
      dockerfile: Dockerfile-dev
    ports:
     - 5435:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask-api:
    image: flask-trans-dev
    build:
      context: back_end/
      dockerfile: Dockerfile-dev
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@db:5432/test
    depends_on:
      - db
    env_file:
      - flask.env

  client:
    image: react-trans-dev
    build:
      context: ./react-app/
      dockerfile: Dockerfile-dev
      args:
        - NODE_ENV=development
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - 3000:3000
    depends_on:
      - flask-api
      - db

  nginx:
    image: nginx-trans-dev
    build:
      context: ./nginx/
      dockerfile: Dockerfile-dev
    ports:
      - 80:80
    depends_on:
      - flask-api
      - client

volumes:
  pgdata:
