version: '3'
services:

  flask-api:
    image: flask-translate
    build:
      context: ./flask_back_end/
      dockerfile: Dockerfile-dev
    volumes:
      - "./flask_back_end/:/usr/src/app"
    ports:
      - 5000:5000

  client:
    image: react-translate
    build:
      context: ./react-app/
      dockerfile: Dockerfile-dev
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - flask-api

  nginx:
    image: nginx-translate
    build:
      context: ./nginx/
      dockerfile: Dockerfile-dev
    ports:
      - 80:80
    depends_on:
      - flask-api
      - client
