"""empty message

Revision ID: 15413d17338b
Revises: 
Create Date: 2019-01-29 11:08:06.632499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15413d17338b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
